const ActionTypes = {
    GET_BOOK: 'GET_BOOK',
    GET_BOOK_RESPONSE: 'GET_BOOK_RESPONSE',

    ADD_BOOK: 'ADD_BOOK',
    ADD_BOOK_RESPONSE: 'ADD_BOOK_RESPONSE',

    UPDATE_BOOK: 'UPDATE_BOOK',
    UPDATE_BOOK_RESPONSE: 'UPDATE_BOOK_RESPONSE',

    DEL_BOOK: 'DEL_BOOK',
    DEL_BOOK_RESPONSE: 'DEL_BOOK_RESPONSE'
}
export default ActionTypes